import { ComponentFixture, TestBed } from '@angular/core/testing';

import { HomeComponent } from './home.component';

describe('HomeComponent', () => {
  let component: HomeComponent;
  let fixture: ComponentFixture<HomeComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [HomeComponent],
    }).compileComponents();

    fixture = TestBed.createComponent(HomeComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});

// Generated by Qodo Gen

describe('HomeComponent', () => {
  // Component initializes with default homeMessage signal value 'Hello, world!'
  it('should initialize homeMessage signal with default value', () => {
    const fixture = TestBed.createComponent(HomeComponent);
    const component = fixture.componentInstance;
    expect(component.homeMessage()).toBe('Hello, world!');
  });

  // keyUpHandler handles special keys like Enter, Escape, Tab
  it('should log special key presses in keyUpHandler', () => {
    const fixture = TestBed.createComponent(HomeComponent);
    const component = fixture.componentInstance;
    const consoleSpy = jest.spyOn(console, 'log');
    const enterEvent = new KeyboardEvent('keyup', { key: 'Enter' });
    const escapeEvent = new KeyboardEvent('keyup', { key: 'Escape' });
    const tabEvent = new KeyboardEvent('keyup', { key: 'Tab' });
    component.keyUpHandler(enterEvent);
    component.keyUpHandler(escapeEvent);
    component.keyUpHandler(tabEvent);
    expect(consoleSpy).toHaveBeenCalledWith('user pressed the Enter key');
    expect(consoleSpy).toHaveBeenCalledWith('user pressed the Escape key');
    expect(consoleSpy).toHaveBeenCalledWith('user pressed the Tab key');
  });
});
