import { CounterComponent } from '../components/counter/counter.component';
import { HighlightCompletedTodoDirective } from './highlight-completed-todo.directive';

describe('HighlightCompletedTodoDirective', () => {
  it('should create an instance', () => {
    const directive = new HighlightCompletedTodoDirective();
    expect(directive).toBeTruthy();
  });
});

// Generated by Qodo Gen

describe('CounterComponent', () => {
  // Initial counter value should be 0
  it('should initialize counter value to 0 when component is created', () => {
    const component = new CounterComponent();
    expect(component.counterValue()).toBe(0);
  });

  // Counter should handle large positive numbers correctly
  it('should increment counter to large positive number when increment called multiple times', () => {
    const component = new CounterComponent();
    const iterations = 1000;
    for (let i = 0; i < iterations; i++) {
      component.increment();
    }
    expect(component.counterValue()).toBe(iterations);
  });

  // Reset method should set counter value back to 0
  it('should reset counter value to 0 when reset is called', () => {
    const component = new CounterComponent();
    component.increment();
    component.reset();
    expect(component.counterValue()).toBe(0);
  });
});
