pull_request_rules:
  - name: Automatic merge when CI passes and reviews approve
    conditions:
      - base = main
      - '#commits-behind >= 0'
      - '#approved-reviews-by >= 0'
      - check-success = CI # replace "CI" with the name of your CI status check
    actions:
      merge:
        method: rebase

  - name: delete head branch after merge but not if other PRs depend on it
    conditions:
      - merged
    actions:
      delete_head_branch:
        force: false
