import { ComponentFixture, TestBed } from '@angular/core/testing';
import { GreetingComponent } from './greeting.component';

describe('GreetingComponent', () => {
  let component: GreetingComponent;
  let fixture: ComponentFixture<GreetingComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [GreetingComponent],
    }).compileComponents();

    fixture = TestBed.createComponent(GreetingComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});

// Generated by Qodo Gen

describe('GreetingComponent', () => {
  // Component initializes with default message 'Hello hello!'
  it('should initialize with default message when no input provided', () => {
    const fixture = TestBed.createComponent(GreetingComponent);
    const component = fixture.componentInstance;
    fixture.detectChanges();

    expect(component.message()).toBe('Hello hello!');
  });
});
