name: Continuous Delivery not Continuous Deployment

on:
  push:
    branches: [ main ]

permissions: read-all

env:
  HUSKY: 0
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3.3.0
        with:
          registry: registry.digitalocean.com/office-hour
          username: ${{ secrets.DIOCEAN_USERNAME }}
          password: ${{ secrets.DIOCEAN_AC }}


      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache node modules of entire Monorepo
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies without break package-lock
        run: npm i --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4

      - run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} nx affected --target=container



        ### Deploy by image
#      - id: string
#        uses: ASzc/change-string-case-action@v6
#        with:
#          string: ${{ github.repository }}

#      - name: Build and push Docker image
#        if: github.event_name == 'push'
#        id: push
#        uses: docker/build-push-action@v6.5.0
#        with:
#          context: .
#          file: ./apps/be-nestjs-app/Dockerfile
#          push: true
#          tags: registry.digitalocean.com/office-hour/${{ steps.string.outputs.lowercase }}:latest
