name: CI

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

permissions:
  id-token: write
  contents: read
  actions: read
env:
  HUSKY: 0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NX_POWERPACK_LICENSE: ${{ secrets.NX_POWERPACK_LICENSE }}
jobs:
  main-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_SPACE_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.DO_SPACE_SECRET_ACCESS_KEY }}
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
          source: custom-cache

      - name: Cache node modules of entire Monorepo
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Install dependencies without break package-lock
        run: npm i --legacy-peer-deps

      # - uses: nrwl/nx-set-shas@v4
      #   with:
      #     workflow-id: 'ci.yml'
      #     main-branch-name: 'main'
      # - run: |
      #     echo "BASE: ${{ env.NX_BASE }}"
      #     echo "HEAD: ${{ env.NX_HEAD }}"

      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      # When you enable task distribution, run the e2e-ci task instead of e2e
      #      - run: npx cypress install
      #      - run: npx nx affected -t lint test build e2e

      #      - id: nx-format-check
      #        run: npx nx format:check
      - id: nx-affected
        run: npx nx affected -t lint test build --base=origin/main --head=$PR_BRANCH_NAME
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - if: ${{ steps.nx-affected.outcome == 'failure' }}
        run: exit 1
